openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: Dev Environment
    url: https://velys.docvisor.dev
info:
  description: Velys Phase 2 APIs
  version: "1.0.0-alpha2"
  title: Velys Phase 2 APIs
  x-logo:
    url: https://docspera.com/assets/D3/pic/Logo-Full-White-Padded.png
    backgroundColor: "#0096FA"
    href: https://docspera.com
  contact:
    email: luca@docspera.com
  license:
    name: Proprietary
tags:
  - name: addpatient
    x-displayName: "Add Patient Workflow"
    description: |
      Add patient APIs described in the architecture diagram section 1.
  - name: hcpchecklist
    x-displayName: "HCP Checklist Workflow"
    description: |
      HCP Checklist APIs described in the architecture diagram section 3.
  - name: intakeform
    x-displayName: "Intake Form Workflow"
    description: |
      Intake Form APIs described in the architecture diagram section 4.
  - name: telehealth
    x-displayName: "Telehealth Appointment Workflow"
    description: |
      Telehealth Appointment APIs described in the architecture diagram section 5.
paths:
  /api/v1/subscriptions/patients:
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - addpatient
      summary: Add a patient subscription
      description: Subscribe to a patient in DocSpera, to trigger data to be sent to DSEP via FHIR channels.
      operationId: createSubscription
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - docspera_patient_id
              properties:
                docspera_patient_id:
                  type: integer
                  description: docspera patient id, as returned from search, to subscribe to
                  example: 212
      responses:
        '200':
          description: success
        '401':
          description: unauthenticated
        '403':
          description: forbidden
  /api/v1/patients:
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - addpatient
      summary: Create a patient in DocSpera
      description: Manually create a patient in DocSpera, usually for manual entry purposes when data is not accessible via EMR.
      operationId: addPatient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicPatientDTO'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicPatientDTO'
        '401':
          description: unauthenticated
        '403':
          description: forbidden
  /api/events:
    get:
      security:
        - BearerAuth: [ ]
      tags:
        - addpatient
      summary: Patient search
      description: Seach for patients in DocSpera by name, mrn, or case name
      operationId: searchPatients
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: User query to search by
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                - event:
                    event_id: 2275351
                    event_type: Surgery
                    bpci_id: 0
                    active: 0
                    thread_id: 0
                    calendar: 2105
                    target: 2105
                    case: Test
                    details: null
                    notes: null
                    setup: null
                    mrn: RP212312312
                    time:
                      start: 20211012181500
                      end: 20211012191500
                    billing: null
                    location:
                      practice_id: 0
                      practice: null
                      address: null
                      building: null
                      room: null
                      status: null
                    attendees:
                      providers:
                        - id: 2105
                          name: Luca Physician4
                          status: Approved
                          type: 1
                          sub: 11
                          specialty: Orthopaedic Surgery
                          avatar: '1'
                      bpci: [ ]
                      reps: [ ]
                    attendee_practice_ids:
                      - 76836
                      - 0
                    post_op:
                      ivf: null
                      ebl: null
                      uop: null
                      dictated: null
                      dictation_code: null
                      notes: null
                    codes:
                      icd: [ ]
                      icd9: [ ]
                      cpt: [ ]
                    patient:
                      patient_id: 16435
                      name: Luca Patient
                      mr: RP212312312
                      dob: 20160505000000
                      status: Tentative
                      phone: '9734137724'
                      insurance:
                        type: '0'
                        policy: '0'
                        group: '0'
                        provider: '0'
                        auth: ''
                        co_pay: '0'
                        deductible: '0'
                      demographics:
                        gender: '0'
                        height: 0
                        weight: 0
                        ethnicity: null
                      supplemental:
                        email: luca@docspera.com
                        ssn: null
                        home:
                          line_1: 10 Wootton Road
                          line_2: null
                          line_3: null
                          line_4: null
                          city:
                            - Essex Fells
                          state: NJ
                          zip: '07021'
                          country: USA
                        emergency: [ ]
                        medical:
                          diabetic: '0'
                          hiv: null
                          conditions:
                            allergies:
                              latex: null
                              other: null
                            anesthesia:
                              type: null
                              other: null
                              redhead: null
                            comorbidities:
                              status: N/A
                              details: ''
                        notes: null
                      bpci_id: 0
                      estimated_discharge: '0'
                      discharged: '0'
                    equipment:
                      devices: [ ]
                      supplemental:
                        orientation: null
                        size: null
                  highlights:
                    - field: patient_mrn
                      value:
                        - <em>RP212312312</em>
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
  /api/v1/patients/{patientId}/checklist:
    put:
      security:
        - BearerAuth: [ ]
      tags:
        - hcpchecklist
      summary: Update HCP Checklist
      description: Update HCP Checklist in DocSpera for a given patient.
      operationId: updateChecklist
      parameters:
        - in: path
          name: patientId
          schema:
            type: integer
          required: true
          description: Patient ID the checklist belongs to
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChecklistDTO"
            example:
              id: 7634
              checklist:
                - id: 200801
                  status: 1
                - id: 200802
                  status: 0
                - id: 200803
                  status: 1
                - id: 200804
                  status: -1
                - id: 20080
                  status: 0
      responses:
        200:
          description: Success
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                errors:
                  checklist:
                    '1':
                      status: This value is required.
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/intake:
    put:
      security:
        - BearerAuth: [ ]
      tags:
        - intakeform
      summary: Send VELYS Patient Intake
      description: Send the VELYS Patient Intake to a patient.
      operationId: sendIntake
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - patientId
              properties:
                patientId:
                  type: integer
                  description: Patient ID the checklist belongs to
                  example: 212
      responses:
        200:
          description: Success
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                errors:
                  docspera_patient_id:
                      status: This value is required.
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /api/v1/patients/{patientId}/appointments/{appointmentId}/telehealth:
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - telehealth
      summary: Create Telehealth Invite for Appointment
      description: Create Telehealth Invite for Appointment.
      operationId: createTelehealthAppointment
      parameters:
        - in: path
          name: patientId
          schema:
            type: integer
          required: true
          description: Patient ID of the appointment.
        - in: path
          name: appointmentId
          schema:
            type: integer
          required: true
          description: Appointment ID to make a telehealth case.
      responses:
        200:
          description: Success
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                errors:
                  docspera_patient_id:
                    status: This value is required.
                  docspera_appointment_id:
                    status: This value is required.
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
    get:
      security:
        - BearerAuth: [ ]
      tags:
        - telehealth
      summary: Get Telehealth Join URL for Appointment
      description: Get Telehealth Join URL for Appointment.
      operationId: getTelehealthAppointmentJoinUrl
      parameters:
        - in: path
          name: patientId
          schema:
            type: integer
          required: true
          description: Patient ID of the telehealth appointment.
        - in: path
          name: appointmentId
          schema:
            type: integer
          required: true
          description: Telehealth Appointment ID to join.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JoinTelehealthResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                errors:
                  docspera_appointment_id:
                    status: Appointment is not a telehealth case.
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
components:
  securitySchemes:
    BearerAuth:
      description: Okta JWT bearer token
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    JoinTelehealthResponse:
      type: object
      required:
        - signed_url
        - expires
      properties:
        signed_url:
          type: string
          format: uri
          description: Signed URL to join the telehealth appointment.
          example: https://telehealth.d4.docspera.com/c/7eae2583-80d9-4029-bde4-fd309a4a27b9
        expires:
          type: integer
          example: 3600
          description: Time in seconds that the signed URL is valid for.
    BasicPatientDTO:
      type: object
      required:
        - name
        - mrn
        - dob
        - dsep_patient_id
      properties:
        name:
          type: object
          required:
            - first
            - last
          properties:
            first:
              type: string
              description: first name
              example: Luca
            last:
              type: string
              description: last name
              example: Santarella
        mrn:
          type: string
          description: patient MRN
        dob:
          type: integer
          description: patient dob, in Ymd format
          example: 19440625
        birth_sex:
          type: string
          description: patinet birth sex, as defined in https://hl7.org/fhir/2018Sep/valueset-birth-sex.html
          enum:
            - "male"
            - "female"
            - "unknown"
        phone:
          type: object
          properties:
            mobile:
              type: string
              description: patient mobile phone
            home:
              type: string
              description: patient home phone
        email:
          type: string
          format: email
          description: patient email
          example: luca@docspera.com
        provider:
          type: integer
          description: provider NPI
          format: NPI
          example: 1928562951
        procedure:
          type: object
          properties:
            name:
              type: string
              description: procedure name
              example: L TKA
            date:
              type: object
              required:
                - start_time
                - end_time
              properties:
                start_time:
                  type: integer
                  description: procedure start datetime, in YmdHis format
                  format: YmdHis
                  example: 20211208090000
                end_time:
                  type: integer
                  description: procedure start datetime, in YmdHis format
                  format: YmdHis
                  example: 20211208093000
            location:
              type: string
              description: lcoation, TBD format
        dsep_patient_id:
          description: DSEP patient id
          type: string
        docspera_patient_id:
          type: integer
          description: docspera patient id
          example: 212
    ChecklistDTO:
      type: object
      required:
        - id
        - checklist
      properties:
        id:
          type: integer
          description: Checklist ID
        checklist:
          type: array
          description: Array of checklist items
          items:
            required:
              - id
              - status
            properties:
              id:
                type: integer
                description: Checklist item ID
              status:
                type: integer
                enum:
                  - -1
                  - 0
                  - 1
                description: Checked status of the checklist item; -1 for N/A, 0 for unchecked, 1 for checked.
    ErrorResponse:
      type: object
      required:
        - status
        - errors
      properties:
        status:
          type: integer
          description: http status code
        errors:
          type: array
          description: array of error messages
